"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { apiJson } from "@/lib/api-client";

type MainOp={code:string;label:string;shortCode?:string|null};
type RecipeSuggestion={status:string;recipeNo:string|null;recipeName:string|null;sourceValue:string|null;needsReview:boolean};
type ProcessTimeSuggestion={status:string;minutes:number|null;needsReview:boolean};
type BatchProposal={eligible:boolean;eligibilityReason:string|null;ruleCode:string|null;batchKey:string|null;warnings:string[];maxJobs:number|null;maxQty:number|null;maxSurfaceDm2:number|null};
type Candidate={planningJobId:number;jobNum:string;program:string|null;part:string|null;revision:string|null;description:string|null;qty:number|null;surfaceDm2:number|null;nextOperation:string|null;nextStOperation:string|null;routePosition:number|null;routeOperationCount:number|null;nextPlanningOperation:MainOp|null;recipeSuggestion:RecipeSuggestion;processTimeSuggestion:ProcessTimeSuggestion;batchProposal:BatchProposal};
type CandidatePayload={total:number;rows:Candidate[];summary:{total:number;eligible:number;totalQty:number;totalSurface:number;review:number}};
type BatchStatus={code:string;label:string;data:Record<string,unknown>};
type BatchRow={id:string;batch_no:string;batch_key:string;main_operation_code:string;main_operation_label:string;recipe_no:string|null;recipe_name:string|null;status:string;job_count:number;total_qty:number|string;total_surface_dm2:number|string;process_time_minutes:number|string|null;batch_rule_code:string|null;created_at:string;jobs:Array<{jobNum:string;part:string;revision:string;qty:number;surfaceDm2:number}>};
type BatchPayload={rows:BatchRow[];statuses:BatchStatus[]};
type ConfigPayload={mainOperations:Array<Record<string,unknown>>};

function fmt(v:number|null|undefined,d=0){return v==null||!Number.isFinite(Number(v))?"—":Number(v).toLocaleString(undefined,{maximumFractionDigits:d})}
function text(v:unknown){return v==null?"":String(v)}

export function BatchWorkbench(){
  const[rows,setRows]=useState<Candidate[]>([]);const[batches,setBatches]=useState<BatchRow[]>([]);const[statuses,setStatuses]=useState<BatchStatus[]>([]);const[mainOperations,setMainOperations]=useState<MainOp[]>([]);
  const[selected,setSelected]=useState<Set<number>>(new Set());const[search,setSearch]=useState("");const[queryText,setQueryText]=useState("");const[mainOperation,setMainOperation]=useState("");const[eligibleOnly,setEligibleOnly]=useState(true);const[manualKey,setManualKey]=useState("");const[notes,setNotes]=useState("");const[loading,setLoading]=useState(true);const[creating,setCreating]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[summary,setSummary]=useState<CandidatePayload["summary"]>({total:0,eligible:0,totalQty:0,totalSurface:0,review:0});

  const loadCandidates=useCallback(async()=>{setLoading(true);setError("");try{const q=new URLSearchParams({limit:"500",offset:"0",search:queryText,mainOperation,eligibleOnly:String(eligibleOnly)});const data=await apiJson<CandidatePayload>(`/api/batch/candidates?${q}`,{cache:"no-store"});setRows(data.rows);setSummary(data.summary);setSelected(current=>new Set([...current].filter(id=>data.rows.some(r=>r.planningJobId===id))))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}},[queryText,mainOperation,eligibleOnly]);
  const loadBatches=useCallback(async()=>{try{const data=await apiJson<BatchPayload>("/api/batches?limit=100",{cache:"no-store"});setBatches(data.rows);setStatuses(data.statuses)}catch(e){setError(e instanceof Error?e.message:String(e))}},[]);
  useEffect(()=>{void loadCandidates()},[loadCandidates]);useEffect(()=>{void loadBatches();void apiJson<ConfigPayload>("/api/config/batch-model",{cache:"no-store"}).then(d=>setMainOperations((d.mainOperations||[]).map(r=>({code:text(r.code),label:text(r.label),shortCode:text((r.data as Record<string,unknown>|undefined)?.shortCode)||null})))).catch(()=>undefined)},[loadBatches]);

  const selectedRows=useMemo(()=>rows.filter(r=>selected.has(r.planningJobId)),[rows,selected]);
  const selectedSummary=useMemo(()=>({jobs:selectedRows.length,qty:selectedRows.reduce((s,r)=>s+(r.qty||0),0),surface:selectedRows.reduce((s,r)=>s+(r.surfaceDm2||0),0),keys:[...new Set(selectedRows.map(r=>r.batchProposal.batchKey||""))],mains:[...new Set(selectedRows.map(r=>r.nextPlanningOperation?.code||""))]}),[selectedRows]);
  const compatible=selectedRows.length>0&&selectedRows.every(r=>r.batchProposal.eligible)&&selectedSummary.mains.length===1&&selectedSummary.keys.length===1;
  function applySearch(e:React.FormEvent){e.preventDefault();setQueryText(search.trim());setSelected(new Set())}
  function toggle(id:number){setSelected(cur=>{const n=new Set(cur);if(n.has(id))n.delete(id);else n.add(id);return n})}
  function selectVisible(){setSelected(new Set(rows.filter(r=>r.batchProposal.eligible).map(r=>r.planningJobId)))}
  async function createBatch(){if(!selectedRows.length)return;setCreating(true);setError("");setMessage("");try{const result=await apiJson<{batchNo:string}>("/api/batches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",planningJobIds:selectedRows.map(r=>r.planningJobId),manualBatchKey:manualKey.trim()||null,notes:notes.trim()||null})});setMessage(`Batch ${result.batchNo} created.`);setSelected(new Set());setManualKey("");setNotes("");await Promise.all([loadCandidates(),loadBatches()])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setCreating(false)}}
  async function updateStatus(id:string,status:string){setError("");try{await apiJson("/api/batches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"status",batchId:id,status})});await loadBatches()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function deleteDraft(id:string){if(!window.confirm("Delete this DRAFT batch?"))return;try{await apiJson("/api/batches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",batchId:id})});await loadBatches()}catch(e){setError(e instanceof Error?e.message:String(e))}}

  return <div className="stack batch-workbench">
    {error?<div className="alert error"><strong>Batch error</strong><span>{error}</span></div>:null}{message?<div className="alert success"><strong>{message}</strong></div>:null}
    <section className="kpi-grid batch-kpis"><article className="kpi-card"><span>CANDIDATES</span><strong>{summary.total}</strong><small>Current configured scan</small></article><article className="kpi-card"><span>ELIGIBLE</span><strong>{summary.eligible}</strong><small>Batch Enabled + rule pass</small></article><article className="kpi-card"><span>QTY</span><strong>{fmt(summary.totalQty)}</strong><small>Candidate quantity</small></article><article className="kpi-card"><span>SURFACE</span><strong>{fmt(summary.totalSurface,1)}</strong><small>dm²</small></article></section>

    <section className="panel"><div className="panel-head batch-head"><div><span className="eyebrow">BATCH CANDIDATES</span><h2>Candidate Jobs</h2></div><div className="batch-filters"><form onSubmit={applySearch}><input placeholder="Search Job / Part / Program…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button" type="submit">Search</button></form><select value={mainOperation} onChange={e=>{setMainOperation(e.target.value);setSelected(new Set())}}><option value="">All Main Operations</option>{mainOperations.map(m=><option value={m.code} key={m.code}>{m.label}</option>)}</select><label className="config-check"><input type="checkbox" checked={eligibleOnly} onChange={e=>{setEligibleOnly(e.target.checked);setSelected(new Set())}}/><span>Eligible only</span></label><button className="button" onClick={selectVisible}>Select visible</button><button className="button" onClick={()=>setSelected(new Set())}>Clear</button></div></div>
      <div className="table-wrap batch-candidate-wrap"><table className="data-table batch-candidate-table"><thead><tr><th></th><th>Job</th><th>Part / Rev</th><th>Next Planning</th><th>Recipe</th><th>Batch Key</th><th>Qty</th><th>Surface</th><th>Process Time</th><th>State</th></tr></thead><tbody>{loading?<tr><td colSpan={10} className="loading-cell">Loading candidates…</td></tr>:rows.length===0?<tr><td colSpan={10} className="empty-state">No candidates match the current filters.</td></tr>:rows.map(r=><tr key={r.planningJobId} className={selected.has(r.planningJobId)?"row-selected":r.batchProposal.warnings.length?"row-warning":""}><td><input type="checkbox" disabled={!r.batchProposal.eligible} checked={selected.has(r.planningJobId)} onChange={()=>toggle(r.planningJobId)}/></td><td><strong className="mono">{r.jobNum}</strong><small className="cell-subtext">{r.program||"—"}</small></td><td><strong>{r.part||"—"}</strong><small className="cell-subtext">{r.revision||"—"}</small></td><td>{r.nextPlanningOperation?<span className="planning-op-badge"><strong>{r.nextPlanningOperation.label}</strong><small>{r.nextPlanningOperation.code}</small></span>:<span className="muted">—</span>}</td><td><div className={`recipe-suggestion ${r.recipeSuggestion.needsReview?"review":""}`}><strong>{r.recipeSuggestion.recipeNo||"—"}</strong><span>{r.recipeSuggestion.recipeName||r.recipeSuggestion.sourceValue||"No recipe"}</span></div></td><td><code className="batch-key-code">{r.batchProposal.batchKey||"—"}</code><small className="cell-subtext">{r.batchProposal.ruleCode||"DEFAULT"}</small></td><td className="num">{fmt(r.qty)}</td><td className="num">{fmt(r.surfaceDm2,1)}</td><td>{r.processTimeSuggestion.minutes==null?<span className="muted">—</span>:<strong>{fmt(r.processTimeSuggestion.minutes,1)} min</strong>}</td><td>{r.batchProposal.eligible?<span className={r.batchProposal.warnings.length?"state-pill review":"state-pill good"}>{r.batchProposal.warnings.length?"REVIEW":"READY"}</span>:<span className="state-pill bad" title={r.batchProposal.eligibilityReason||""}>BLOCKED</span>}</td></tr>)}</tbody></table></div>
    </section>

    <section className="panel batch-builder"><div className="panel-head"><div><span className="eyebrow">BATCH BUILDER</span><h2>{selectedRows.length?`${selectedRows.length} Selected Job(s)`:"Select Candidate Jobs"}</h2></div><span className={`state-pill ${compatible?"good":"neutral"}`}>{compatible?"KEY COMPATIBLE":"CHECK SELECTION"}</span></div><div className="batch-builder-grid"><div className="batch-selection-metrics"><div><span>JOBS</span><strong>{selectedSummary.jobs}</strong></div><div><span>QTY</span><strong>{fmt(selectedSummary.qty)}</strong></div><div><span>SURFACE</span><strong>{fmt(selectedSummary.surface,1)}</strong></div><div><span>AUTO KEY</span><strong className="mono">{selectedSummary.keys.length===1?selectedSummary.keys[0]||"—":selectedSummary.keys.length>1?"MIXED":"—"}</strong></div></div><label><span>Manual Batch Key (optional)</span><input placeholder="Leave blank to use configured Auto Key" value={manualKey} onChange={e=>setManualKey(e.target.value)}/></label><label><span>Notes</span><input placeholder="Optional planner note" value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button primary" disabled={creating||!selectedRows.length||(!compatible&&!manualKey.trim())} onClick={()=>void createBatch()}>{creating?"Creating…":"Create Batch"}</button></div></section>

    <section className="panel"><div className="panel-head"><div><span className="eyebrow">RECENT BATCHES</span><h2>Planning Batches</h2></div><button className="button" onClick={()=>void loadBatches()}>Refresh</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Batch No.</th><th>Main Operation</th><th>Recipe</th><th>Batch Key</th><th>Jobs</th><th>Qty</th><th>Surface</th><th>Time</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>{batches.map(b=><tr key={b.id}><td><strong className="mono">{b.batch_no}</strong></td><td><strong>{b.main_operation_label||b.main_operation_code}</strong><small className="cell-subtext">{b.main_operation_code}</small></td><td><strong>{b.recipe_no||"—"}</strong><small className="cell-subtext">{b.recipe_name||""}</small></td><td><code className="batch-key-code">{b.batch_key}</code></td><td>{b.job_count}</td><td className="num">{fmt(Number(b.total_qty))}</td><td className="num">{fmt(Number(b.total_surface_dm2),1)}</td><td>{b.process_time_minutes==null?"—":`${fmt(Number(b.process_time_minutes),1)} min`}</td><td><select value={b.status} onChange={e=>void updateStatus(b.id,e.target.value)}>{statuses.length?statuses.map(s=><option key={s.code} value={s.code}>{s.label}</option>):<option>{b.status}</option>}</select></td><td>{new Date(b.created_at).toLocaleString()}</td><td>{statuses.find(s=>s.code===b.status)?.data?.allowDelete===true?<button className="button danger-soft" onClick={()=>void deleteDraft(b.id)}>Delete</button>:null}</td></tr>)}</tbody></table></div></section>
  </div>
}
