"use client";

import { useEffect, useState } from "react";
import { apiJson } from "@/lib/api-client";

type SettingRow={setting_key:string;category:string;label:string;data_type:string;value_json:unknown;enabled:boolean;description:string|null};
type ItemRow={id:string;category:string;code:string;label:string;enabled:boolean;sort_order:number;data:Record<string,unknown>};
function displayValue(v:unknown){return typeof v==="string"?v:JSON.stringify(v??null)}
function parseValue(text:string,type:string):unknown{if(type==="boolean")return text==="true";if(type==="number"){const n=Number(text);if(!Number.isFinite(n))throw new Error("Enter a valid number.");return n}if(type==="json")return JSON.parse(text);return text}

export function CapacityModelConsole(){
  const[settings,setSettings]=useState<SettingRow[]>([]);const[resources,setResources]=useState<ItemRow[]>([]);const[edit,setEdit]=useState<Record<string,string>>({});const[resourceEdit,setResourceEdit]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[message,setMessage]=useState("");
  async function load(){setLoading(true);setError("");try{const[a,b]=await Promise.all([apiJson<{rows:SettingRow[]}>('/api/config?entity=settings&filter=CAPACITY',{cache:'no-store'}),apiJson<{rows:ItemRow[]}>('/api/config?entity=items&filter=CAPACITY_RESOURCE',{cache:'no-store'})]);const sr=a.rows.filter(x=>x.category==='CAPACITY_MODEL');const rr=b.rows.filter(x=>x.category==='CAPACITY_RESOURCE');setSettings(sr);setResources(rr);setEdit(Object.fromEntries(sr.map(x=>[x.setting_key,displayValue(x.value_json)])));setResourceEdit(Object.fromEntries(rr.map(x=>[x.id,JSON.stringify(x.data,null,2)])))}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function saveSetting(r:SettingRow){setError("");setMessage("");try{const value=parseValue(edit[r.setting_key]??'',r.data_type);await apiJson('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entity:'settings',action:'upsert',row:{settingKey:r.setting_key,category:r.category,label:r.label,dataType:r.data_type,value,enabled:r.enabled,description:r.description}})});setMessage(`${r.label} saved.`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function saveResource(r:ItemRow){setError("");setMessage("");try{const data=JSON.parse(resourceEdit[r.id]||'{}');await apiJson('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entity:'items',action:'upsert',row:{category:r.category,code:r.code,label:r.label,parentCode:null,enabled:r.enabled,sortOrder:r.sort_order,data}})});setMessage(`${r.label} capacity saved.`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  return <div className="stack">
    {error?<div className="alert error"><strong>Capacity configuration error</strong><span>{error}</span></div>:null}{message?<div className="alert success"><strong>{message}</strong></div>:null}
    <section className="panel"><div className="panel-head"><div><span className="eyebrow">CFG-95 / FINITE CAPACITY</span><h2>Capacity Scheduler Settings</h2></div><button className="button" onClick={()=>void load()}>Refresh</button></div>
      <div className="output-config-note"><strong>Configuration-first scheduling · v017 baseline active</strong><span>Physical slots, shared concurrency, changeover and batch capacity are editable configuration. Masking, Unmasking, NDT, Inspection and Rework now have baseline finite resources; source-approved 6 Flybars / 3 concurrent process blocks and 4 painting cabins remain unchanged.</span></div>
      <div className="table-wrap"><table className="erp-table"><thead><tr><th>Setting</th><th>Key</th><th>Type</th><th>Value</th><th>Description</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="loading-cell">Loading capacity settings…</td></tr>:settings.map(r=><tr key={r.setting_key}><td><strong>{r.label}</strong></td><td><code>{r.setting_key}</code></td><td>{r.data_type}</td><td>{r.data_type==='boolean'?<select value={edit[r.setting_key]??'false'} onChange={e=>setEdit(x=>({...x,[r.setting_key]:e.target.value}))}><option value="true">true</option><option value="false">false</option></select>:r.setting_key==='capacity.unmappedResourcePolicy'?<select value={edit[r.setting_key]??'REVIEW_UNCONSTRAINED'} onChange={e=>setEdit(x=>({...x,[r.setting_key]:e.target.value}))}><option value="REVIEW_UNCONSTRAINED">REVIEW_UNCONSTRAINED</option><option value="BLOCK">BLOCK</option></select>:<input value={edit[r.setting_key]??''} onChange={e=>setEdit(x=>({...x,[r.setting_key]:e.target.value}))}/>}</td><td><span className="subcell output-config-description">{r.description||'—'}</span></td><td><button className="button" onClick={()=>void saveSetting(r)}>Save</button></td></tr>)}</tbody></table></div>
    </section>
    <section className="panel"><div className="panel-head"><div><span className="eyebrow">RESOURCE CAPACITY MASTER</span><h2>Physical Slots & Shared Concurrency</h2></div><span className="record-count"><strong>{resources.length}</strong> resources</span></div>
      <div className="table-wrap tall"><table className="erp-table compact"><thead><tr><th>Resource</th><th>Order</th><th>Capacity JSON</th><th></th></tr></thead><tbody>{resources.map(r=><tr key={r.id}><td><strong>{r.label}</strong><small className="subcell mono">{r.code}</small></td><td className="num">{r.sort_order}</td><td><textarea className="capacity-json" value={resourceEdit[r.id]??'{}'} onChange={e=>setResourceEdit(x=>({...x,[r.id]:e.target.value}))}/></td><td><button className="button" onClick={()=>void saveResource(r)}>Save</button></td></tr>)}</tbody></table></div>
    </section>
  </div>
}
