"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { apiJson } from "@/lib/api-client";

type Batch={id:string;batch_no:string;main_operation_code:string;status:string;version:number;job_count:number;total_surface_dm2:number|string;done_jobs:number;running_jobs:number;actual_start:string|null;actual_end:string|null};
type Execution={id:string;batch_id:string;job_num:string;main_operation_code:string;route_occurrence_key:string;route_position:number|null;state:string;actual_start:string|null;actual_end:string|null;good_qty:number|string|null;reject_qty:number|string|null;version:number;batch_no:string|null;batch_status:string|null;batch_version:number|null};
type Inspection={id:string;job_num:string;route_occurrence_key:string;route_position:number|null;operation_code:string;inspection_type:string;status:string;actual_start:string|null;actual_end:string|null;result_code:string|null;notes:string|null;version:number;updated_at:string};
function fmt(v:string|null){if(!v)return"—";const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString():v;}

export function ExecutionInspectionWorkbench(){
 const[batches,setBatches]=useState<Batch[]>([]);const[execRows,setExecRows]=useState<Execution[]>([]);const[inspections,setInspections]=useState<Inspection[]>([]);const[error,setError]=useState("");const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);
 const[batchId,setBatchId]=useState("");const[jobNum,setJobNum]=useState("");const[inspectionJob,setInspectionJob]=useState("");const[occurrence,setOccurrence]=useState("");const[opCode,setOpCode]=useState("");const[inspStatus,setInspStatus]=useState("IN_PROGRESS");const[inspType,setInspType]=useState("INTERMEDIATE");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const[e,i]=await Promise.all([apiJson<{rows:Execution[];batches:Batch[]}>("/api/execution",{cache:"no-store"}),apiJson<{rows:Inspection[]}>("/api/inspection",{cache:"no-store"})]);setBatches(e.batches);setExecRows(e.rows);setInspections(i.rows);}catch(x){setError(x instanceof Error?x.message:String(x));}finally{setBusy(false);}},[]);
 useEffect(()=>{void load();},[load]);useEffect(()=>{if(!batchId&&batches[0])setBatchId(batches[0].id);},[batches,batchId]);
 const batch=useMemo(()=>batches.find(b=>b.id===batchId)||null,[batches,batchId]);
 async function act(action:"START"|"COMPLETE"|"HOLD"|"RESET"){if(!batch)return;setBusy(true);setError("");setMsg("");try{const r=await apiJson<{batchNo:string;batchStatus:string;batchVersion:number}>("/api/execution",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({batchId:batch.id,jobNum:jobNum.trim()||null,expectedBatchVersion:batch.version,action})});setMsg(`${r.batchNo}: ${r.batchStatus} · v${r.batchVersion}`);await load();}catch(x){setError(x instanceof Error?x.message:String(x));}finally{setBusy(false);}}
 async function saveInspection(){if(!inspectionJob.trim()||!occurrence.trim()||!opCode.trim()){setError("Inspection requires Job, Occurrence Key and Operation Code.");return;}setBusy(true);setError("");setMsg("");try{const old=inspections.find(i=>i.job_num.trim().toUpperCase()===inspectionJob.trim().toUpperCase()&&i.route_occurrence_key===occurrence.trim());const r=await apiJson<{status:string;version:number}>("/api/inspection",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobNum:inspectionJob.trim(),routeOccurrenceKey:occurrence.trim(),operationCode:opCode.trim(),inspectionType:inspType,status:inspStatus,expectedVersion:old?.version??null})});setMsg(`Inspection ${inspectionJob} / ${occurrence}: ${r.status} · v${r.version}`);await load();}catch(x){setError(x instanceof Error?x.message:String(x));}finally{setBusy(false);}}
 return <div className="stack">
  {error?<div className="alert error"><strong>ERP execution conflict</strong><span>{error}</span></div>:null}{msg?<div className="alert success"><strong>Saved</strong><span>{msg}</span></div>:null}
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">v026.4 · ACTUAL EXECUTION</span><h2>Job / Batch Execution Ledger</h2><p className="subcell">Actual start/end is recorded at Job + route occurrence. Batch status rolls forward only through the configured lifecycle.</p></div><button className="button" onClick={()=>void load()} disabled={busy}>{busy?"Loading…":"Refresh"}</button></div>
   <div className="whatif-input-grid"><label><span>Batch</span><select value={batchId} onChange={e=>setBatchId(e.target.value)}>{batches.map(b=><option key={b.id} value={b.id}>{b.batch_no} · {b.main_operation_code} · {b.status} · v{b.version}</option>)}</select></label><label><span>Job (optional)</span><input value={jobNum} onChange={e=>setJobNum(e.target.value)} placeholder="blank = all Batch Jobs"/></label><div className="whatif-actions"><button className="button primary" onClick={()=>void act("START")} disabled={!batch||busy||!["SCHEDULED","STARTED"].includes(batch.status)}>Start</button><button className="button" onClick={()=>void act("COMPLETE")} disabled={!batch||busy||batch.status!=="STARTED"}>Complete</button><button className="button" onClick={()=>void act("HOLD")} disabled={!batch||busy||batch.status!=="STARTED"}>Hold</button><small>{batch?`${batch.job_count} jobs · ${Number(batch.total_surface_dm2||0).toLocaleString()} dm² · ${batch.done_jobs||0} done / ${batch.running_jobs||0} running`:"No executable Batch"}</small></div></div>
   <div className="table-wrap"><table className="erp-table compact"><thead><tr><th>Batch</th><th>Job</th><th>Main</th><th>Occurrence</th><th>State</th><th>Actual Start</th><th>Actual End</th><th>Good</th><th>Reject</th><th>Version</th></tr></thead><tbody>{!execRows.length?<tr><td colSpan={10} className="empty-state">No actual execution captured yet.</td></tr>:execRows.map(r=><tr key={r.id}><td className="mono">{r.batch_no||"—"}</td><td><strong className="mono">{r.job_num}</strong></td><td>{r.main_operation_code}</td><td className="mono">{r.route_occurrence_key}</td><td><span className={`state-pill ${r.state==="DONE"?"good":r.state==="IN_PROGRESS"?"info":r.state==="HOLD"?"warn":"neutral"}`}>{r.state}</span></td><td>{fmt(r.actual_start)}</td><td>{fmt(r.actual_end)}</td><td>{r.good_qty??"—"}</td><td>{r.reject_qty??"—"}</td><td>v{r.version}</td></tr>)}</tbody></table></div>
  </section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">v026.4 · INSPECTION ACTUAL</span><h2>Intermediate / Final Inspection Ledger</h2><p className="subcell">Inspection is tracked by physical-route occurrence. FAILED remains visible and blocks ST Output forecast until disposition changes.</p></div></div>
   <div className="whatif-input-grid"><label><span>Job</span><input value={inspectionJob} onChange={e=>setInspectionJob(e.target.value)}/></label><label><span>Occurrence Key</span><input value={occurrence} onChange={e=>setOccurrence(e.target.value)} placeholder="INSPPA#1"/></label><label><span>Operation</span><input value={opCode} onChange={e=>setOpCode(e.target.value)} placeholder="INSPPA"/></label><label><span>Type</span><select value={inspType} onChange={e=>setInspType(e.target.value)}><option>INTERMEDIATE</option><option>FINAL</option></select></label><label><span>Status</span><select value={inspStatus} onChange={e=>setInspStatus(e.target.value)}><option>WAITING</option><option>IN_PROGRESS</option><option>PASSED</option><option>FAILED</option><option>SKIPPED</option></select></label><div className="whatif-actions"><button className="button primary" onClick={()=>void saveInspection()} disabled={busy}>Save Inspection</button></div></div>
   <div className="table-wrap"><table className="erp-table compact"><thead><tr><th>Job</th><th>Occurrence</th><th>Operation</th><th>Type</th><th>Status</th><th>Actual Start</th><th>Actual End</th><th>Result</th><th>Version</th></tr></thead><tbody>{!inspections.length?<tr><td colSpan={9} className="empty-state">No inspection actual captured yet.</td></tr>:inspections.map(i=><tr key={i.id}><td><strong className="mono">{i.job_num}</strong></td><td className="mono">{i.route_occurrence_key}</td><td>{i.operation_code}</td><td>{i.inspection_type}</td><td><span className={`state-pill ${i.status==="PASSED"?"good":i.status==="FAILED"?"bad":i.status==="IN_PROGRESS"?"info":"neutral"}`}>{i.status}</span></td><td>{fmt(i.actual_start)}</td><td>{fmt(i.actual_end)}</td><td>{i.result_code||"—"}</td><td>v{i.version}</td></tr>)}</tbody></table></div>
  </section>
 </div>;
}
