import { query } from "@/lib/db";
import { calculateStOutputTarget } from "@/lib/st-output-engine";
import { getStOutputModel } from "@/lib/st-output-model";
import { plantToday } from "@/lib/plant-time";

export type ErpExceptionSeverity="CRITICAL"|"HIGH"|"MEDIUM"|"LOW";
export type ErpException={id:string;code:string;severity:ErpExceptionSeverity;entityType:string;entityId:string;jobNum:string|null;batchNo:string|null;title:string;detail:string;action:string;createdAt:string|null};
export type ErpControlTowerResult={generatedAt:string;targetDate:string;cutoffTime:string;targetValue:number;kpis:{activeBatches:number;activeReservations:number;runningJobs:number;failedInspections:number;unscheduledCommitments:number;outputForecastDm2:number;outputGapDm2:number;lateDm2:number;blockedDm2:number;timeUnknownDm2:number;p80RiskJobs:number;insufficientHistoryJobs:number;exceptionCount:number;criticalCount:number};exceptions:ErpException[];output:{achievementPct:number;countedJobs:number;lateJobs:number;blockedJobs:number;timeUnknownJobs:number};warnings:string[]};

function severityRank(x:ErpExceptionSeverity){return x==="CRITICAL"?4:x==="HIGH"?3:x==="MEDIUM"?2:1;}

export async function buildErpControlTower(targetDate?:string):Promise<ErpControlTowerResult>{
 const model=await getStOutputModel();const date=targetDate||plantToday(model.timezoneOffsetMinutes);
 const saved=await query<{target_value:string|null;cutoff_time:string|null}>(`SELECT target_value::text,cutoff_time::text FROM st_output_targets WHERE target_date=$1::date AND metric_code=$2 LIMIT 1`,[date,model.metricCode]);
 const targetValue=Math.max(0,Number(saved.rows[0]?.target_value??model.defaultTargetValue)||0);const cutoffTime=String(saved.rows[0]?.cutoff_time||model.defaultCutoffTime).slice(0,5);
 const [batchStats,resStats,execStats,inspectionStats,unscheduledCount,unscheduled,holds,failed,dupJobs,audit]=await Promise.all([
  query<{count:number}>(`SELECT count(*)::int AS count FROM planning_batches WHERE status NOT IN ('COMPLETED','CANCELLED')`),
  query<{count:number}>(`SELECT count(*)::int AS count FROM erp_schedule_reservations WHERE state='ACTIVE'`),
  query<{count:number}>(`SELECT count(*)::int AS count FROM erp_job_operation_execution WHERE state='IN_PROGRESS'`),
  query<{count:number}>(`SELECT count(*)::int AS count FROM erp_inspection_events WHERE status='FAILED'`),
  query<{count:number}>(`SELECT count(DISTINCT b.id)::int AS count FROM planning_batches b JOIN erp_job_commitments c ON c.batch_id=b.id AND c.state='ACTIVE' LEFT JOIN erp_schedule_reservations r ON r.batch_id=b.id AND r.state='ACTIVE' WHERE b.status IN ('DRAFT','READY','SCHEDULED') AND r.id IS NULL`),
  query(`SELECT b.id::text,b.batch_no,b.main_operation_code,b.status,b.created_at::text,count(c.id)::int AS commitment_count FROM planning_batches b JOIN erp_job_commitments c ON c.batch_id=b.id AND c.state='ACTIVE' LEFT JOIN erp_schedule_reservations r ON r.batch_id=b.id AND r.state='ACTIVE' WHERE b.status IN ('DRAFT','READY','SCHEDULED') GROUP BY b.id HAVING count(r.id)=0 ORDER BY b.created_at LIMIT 200`),
  query(`SELECT e.id::text,e.job_num,e.main_operation_code,e.route_occurrence_key,e.updated_at::text,b.batch_no FROM erp_job_operation_execution e LEFT JOIN planning_batches b ON b.id=e.batch_id WHERE e.state='HOLD' ORDER BY e.updated_at DESC LIMIT 200`),
  query(`SELECT id::text,job_num,route_occurrence_key,operation_code,updated_at::text FROM erp_inspection_events WHERE status='FAILED' ORDER BY updated_at DESC LIMIT 200`),
  query(`SELECT upper(btrim(job_num)) AS job_num,count(*)::int AS row_count FROM v_active_planning_jobs WHERE NULLIF(btrim(job_num),'') IS NOT NULL GROUP BY upper(btrim(job_num)) HAVING count(*)>1 ORDER BY count(*) DESC,upper(btrim(job_num)) LIMIT 200`),
  query(`SELECT event_type,entity_type,entity_id,job_num,created_at::text FROM erp_audit_events ORDER BY created_at DESC LIMIT 20`),
 ]);
 const output=await calculateStOutputTarget({targetDate:date,cutoffTime,targetValue,limit:model.maxScanJobs});
 const exceptions:ErpException[]=[];
 for(const r of unscheduled.rows as Record<string,unknown>[])exceptions.push({id:`UNSCHEDULED:${r.id}`,code:"ACTIVE_COMMITMENT_UNSCHEDULED",severity:"HIGH",entityType:"BATCH",entityId:String(r.id),jobNum:null,batchNo:String(r.batch_no),title:`${r.batch_no} has no ERP resource reservation`,detail:`${r.main_operation_code} · ${r.status} · ${r.commitment_count} active Job commitments`,action:"Open SCH-20 and reserve a finite resource/time slot.",createdAt:r.created_at?String(r.created_at):null});
 for(const r of holds.rows as Record<string,unknown>[])exceptions.push({id:`HOLD:${r.id}`,code:"EXECUTION_HOLD",severity:"HIGH",entityType:"JOB_OPERATION_EXECUTION",entityId:String(r.id),jobNum:String(r.job_num),batchNo:r.batch_no?String(r.batch_no):null,title:`${r.job_num} is on HOLD`,detail:`${r.main_operation_code} · ${r.route_occurrence_key}`,action:"Resolve the production hold or update the execution state.",createdAt:r.updated_at?String(r.updated_at):null});
 for(const r of failed.rows as Record<string,unknown>[])exceptions.push({id:`INSP:${r.id}`,code:"INSPECTION_FAILED",severity:"CRITICAL",entityType:"INSPECTION",entityId:String(r.id),jobNum:String(r.job_num),batchNo:null,title:`${r.job_num} failed ${r.operation_code}`,detail:`Occurrence ${r.route_occurrence_key}`,action:"Disposition the inspection before this Job can contribute to ST Output.",createdAt:r.updated_at?String(r.updated_at):null});
 for(const r of dupJobs.rows as Record<string,unknown>[])exceptions.push({id:`DUP:${r.job_num}`,code:"DUPLICATE_ACTIVE_JOB",severity:"MEDIUM",entityType:"JOB",entityId:String(r.job_num),jobNum:String(r.job_num),batchNo:null,title:`Duplicate active source rows for ${r.job_num}`,detail:`${r.row_count} active Planning rows; Current Job Read Model suppresses duplicates deterministically.`,action:"Correct upstream source data; ERP uses the latest source row until then.",createdAt:null});
 for(const row of output.rows){
    if(row.outputBucket==="LATE")exceptions.push({id:`OUT:LATE:${row.outputKey}`,code:"OUTPUT_LATE",severity:"HIGH",entityType:"OUTPUT_KEY",entityId:row.outputKey,jobNum:row.jobNum,batchNo:null,title:`${row.jobNum} projected late`,detail:`Final ${row.finalGateCode||"Gate"} ETA ${row.projectedFinsstAt||"unknown"}`,action:"Review Critical Action / bottleneck and recovery in OUT-40.",createdAt:null});
    else if(row.outputBucket==="BLOCKED")exceptions.push({id:`OUT:BLOCK:${row.outputKey}`,code:"OUTPUT_BLOCKED",severity:"CRITICAL",entityType:"OUTPUT_KEY",entityId:row.outputKey,jobNum:row.jobNum,batchNo:null,title:`${row.jobNum} blocked before Final Gate`,detail:row.outputBasis,action:"Open Job Route and resolve the blocking dependency/inspection.",createdAt:null});
    else if(row.outputBucket==="TIME_UNKNOWN")exceptions.push({id:`OUT:TIME:${row.outputKey}`,code:"OUTPUT_TIME_UNKNOWN",severity:"MEDIUM",entityType:"OUTPUT_KEY",entityId:row.outputKey,jobNum:row.jobNum,batchNo:null,title:`${row.jobNum} Final ETA unknown`,detail:row.outputBasis,action:"Configure missing process/inspection time or record actual completion.",createdAt:null});
    if(row.etaRiskStatus==="P80_AFTER_CUTOFF")exceptions.push({id:`ETA:P80:${row.outputKey}`,code:"PREDICTIVE_P80_CUTOFF_RISK",severity:"MEDIUM",entityType:"OUTPUT_KEY",entityId:row.outputKey,jobNum:row.jobNum,batchNo:null,title:`${row.jobNum} has P80 cutoff risk`,detail:`P50 ${row.projectedFinsstAt||"unknown"} · P80 ${row.projectedP80At||"unknown"} · confidence ${row.etaConfidence}`,action:"Review recovery options or protect capacity before the P80 risk becomes a late Job.",createdAt:null});
  }
 exceptions.sort((a,b)=>severityRank(b.severity)-severityRank(a.severity)||(b.createdAt||"").localeCompare(a.createdAt||""));
 const criticalCount=exceptions.filter(x=>x.severity==="CRITICAL").length;
 return{generatedAt:new Date().toISOString(),targetDate:date,cutoffTime,targetValue,kpis:{activeBatches:Number(batchStats.rows[0]?.count||0),activeReservations:Number(resStats.rows[0]?.count||0),runningJobs:Number(execStats.rows[0]?.count||0),failedInspections:Number(inspectionStats.rows[0]?.count||0),unscheduledCommitments:Number(unscheduledCount.rows[0]?.count||0),outputForecastDm2:output.summary.totalForecastSurface,outputGapDm2:Math.max(0,targetValue-output.summary.totalForecastSurface),lateDm2:output.summary.lateSurface,blockedDm2:output.summary.blockedSurface,timeUnknownDm2:output.summary.timeUnknownSurface,p80RiskJobs:output.rows.filter(x=>x.etaRiskStatus==="P80_AFTER_CUTOFF").length,insufficientHistoryJobs:output.rows.filter(x=>x.etaRiskStatus==="INSUFFICIENT_HISTORY").length,exceptionCount:exceptions.length,criticalCount},exceptions:exceptions.slice(0,500),output:{achievementPct:targetValue>0?output.summary.totalForecastSurface/targetValue*100:0,countedJobs:output.ledgerSummary.countedJobs,lateJobs:output.ledgerSummary.lateJobs,blockedJobs:output.ledgerSummary.blockedJobs,timeUnknownJobs:output.ledgerSummary.timeUnknownJobs},warnings:[...output.warnings,`RECENT_AUDIT_EVENTS:${audit.rows.length}`]};
}
