-- ST Planning v012 — Seeded hierarchy masters
-- Source-driven baseline. Planner labels are role placeholders because source files do not contain person names.


INSERT INTO config_items (category,code,label,sort_order,data) VALUES
(E'MAIN_OPERATION',E'CMSA',E'CMSA',10,E'{"planningOrder":10,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"CMSA","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"CMSA","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'CHEMMILL',E'Chemical Milling',20,E'{"planningOrder":20,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"CHEMMILL","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"CHEMMILL","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'CPBILP',E'CPBILP',30,E'{"planningOrder":30,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"CPBILP","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"CPBILP","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'CPBILP_A',E'CPBILP-A',40,E'{"planningOrder":40,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"CPBILP_A","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"CPBILP-A","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'PIONBL',E'PIONBL',50,E'{"planningOrder":50,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PIONBL","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PIONBL","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'DE_ANODIZING',E'De-Anodizing',60,E'{"planningOrder":60,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"DE_ANODI","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"DE-ANODIZING","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'V_A_SHPN',E'Auto Shot Peening',70,E'{"planningOrder":70,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"V_A_SHPN","color":"#0369A1","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"V_A-SHPN","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'MANUALSP',E'Manual Shot Peening',80,E'{"planningOrder":80,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"MANUALSP","color":"#2563EB","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"MANUALSP","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'CLASP',E'CLASP',90,E'{"planningOrder":90,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"CLASP","color":"#2563EB","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"CLASP","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'BSAUNSLD',E'BSA Unsealed',100,E'{"planningOrder":100,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"BSAUNSLD","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"BSAUNSLD","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'TSAUNSLD',E'TSA Unsealed',110,E'{"planningOrder":110,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"TSAUNSLD","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"TSAUNSLD","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'BSASLD',E'BSA Sealed',120,E'{"planningOrder":120,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"BSASLD","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"BSASLD","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'TSASLD',E'TSA Sealed',130,E'{"planningOrder":130,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"TSASLD","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"TSASLD","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'CCNV_IM',E'Chemical Conversion - IM',140,E'{"planningOrder":140,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"CCNV_IM","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"CCNV-IM","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'CCNV_IA',E'Chemical Conversion - IA',150,E'{"planningOrder":150,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"CCNV_IA","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"CCNV-IA","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'ANOD_CCNV_FB',E'Anodizing / CCNV Flybar',160,E'{"planningOrder":160,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"ANOD_CCN","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"ANOD/CCNV FB","seedVersion":"v012","needsReview":true,"derivedOrContextual":true}'::jsonb),
(E'MAIN_OPERATION',E'PASS_BRTG',E'Passivation / Brightening',170,E'{"planningOrder":170,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PASS_BRT","color":"#0E7490","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PASS/\\nBRTG","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'FMSKG_CM',E'Fluid Masking - Chemical Mill',180,E'{"planningOrder":180,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"FMSKG_CM","color":"#D97706","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"FMSKG-CM","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'SIPC',E'Sirius Precleaning',190,E'{"planningOrder":190,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"SIPC","color":"#0891B2","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"SIPC","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'SI_SEAL',E'SI Seal',200,E'{"planningOrder":200,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"SI_SEAL","color":"#0F766E","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"SI-SEAL","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'STRIP',E'Strip',210,E'{"planningOrder":210,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"STRIP","color":"#7E22CE","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"STRIP","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'STRIP_HE_BAKE',E'Strip + He-Bake',220,E'{"planningOrder":220,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"STRIP_HE","color":"#BE185D","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"STRIP | HE-BAKE","seedVersion":"v012","needsReview":true,"derivedOrContextual":true}'::jsonb),
(E'MAIN_OPERATION',E'HE_BAKE_M_DBLST',E'He-Bake before Manual Blasting',230,E'{"planningOrder":230,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"HE_BAKE_","color":"#BE185D","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"HE-BAKE | M-DBLST","seedVersion":"v012","needsReview":true,"derivedOrContextual":true}'::jsonb),
(E'MAIN_OPERATION',E'A_DBLST',E'Auto Blasting',240,E'{"planningOrder":240,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"A_DBLST","color":"#15803D","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"A-DBLST","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'M_DBLST',E'Manual Blasting',250,E'{"planningOrder":250,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"M_DBLST","color":"#16A34A","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"M-DBLST","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'PLA_ZINI',E'ZnNi Plating',260,E'{"planningOrder":260,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PLA_ZINI","color":"#7E22CE","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PLA-ZiNi","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'PLA_ZINI_HE_BAKE',E'ZnNi + He-Bake',270,E'{"planningOrder":270,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PLA_ZINI","color":"#BE185D","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PLA-ZiNi | HE-BAKE","seedVersion":"v012","needsReview":true,"derivedOrContextual":true}'::jsonb),
(E'MAIN_OPERATION',E'PLA_CC',E'Plating / Chromate Coating',280,E'{"planningOrder":280,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PLA_CC","color":"#7E22CE","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PLA-CC","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'PRIMER',E'Primer',290,E'{"planningOrder":290,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PRIMER","color":"#C026D3","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PRIMER","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'PRIMER2',E'Primer 2',300,E'{"planningOrder":300,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PRIMER2","color":"#C026D3","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PRIMER2","seedVersion":"v012","needsReview":true,"derivedOrContextual":true}'::jsonb),
(E'MAIN_OPERATION',E'PRIMER3',E'Primer 3',310,E'{"planningOrder":310,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PRIMER3","color":"#C026D3","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PRIMER3","seedVersion":"v012","needsReview":true,"derivedOrContextual":true}'::jsonb),
(E'MAIN_OPERATION',E'TOPCOAT1',E'Topcoat 1',320,E'{"planningOrder":320,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"TOPCOAT1","color":"#C026D3","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"TOPCOAT1","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'TOPCOAT2',E'Topcoat 2',330,E'{"planningOrder":330,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"TOPCOAT2","color":"#C026D3","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"TOPCOAT2","seedVersion":"v012","needsReview":true,"derivedOrContextual":true}'::jsonb),
(E'MAIN_OPERATION',E'ANTI_ABRASION',E'Anti-Abrasion',340,E'{"planningOrder":340,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"ANTI_ABR","color":"#C026D3","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"ANTI-ABRASION","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'PAINT_MARKING',E'Paint Marking',350,E'{"planningOrder":350,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PAINT_MA","color":"#C026D3","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"PAINT MARKING","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'VARNISH',E'Varnish',360,E'{"planningOrder":360,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"VARNISH","color":"#C026D3","sourceBasis":"SirusClean_Painting_MasterList header","sourceHeader":"VARNISH","seedVersion":"v012","needsReview":false}'::jsonb),
(E'MAIN_OPERATION',E'MASKING',E'Masking',400,E'{"planningOrder":400,"planningEnabled":true,"scheduleEnabled":false,"batchEnabled":false,"shortCode":"MASKING","color":"#D97706","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'UNMASKING',E'Unmasking',410,E'{"planningOrder":410,"planningEnabled":true,"scheduleEnabled":false,"batchEnabled":false,"shortCode":"UNMASKIN","color":"#D97706","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'HE_BAKE',E'He-Bake',420,E'{"planningOrder":420,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"HE_BAKE","color":"#BE185D","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'NDT',E'NDT',430,E'{"planningOrder":430,"planningEnabled":false,"scheduleEnabled":true,"batchEnabled":false,"shortCode":"NDT","color":"#475569","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'ST_INSPECTION',E'ST Inspection',440,E'{"planningOrder":440,"planningEnabled":false,"scheduleEnabled":false,"batchEnabled":false,"shortCode":"ST_INSPE","color":"#475569","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'ST_FINAL',E'ST Final Inspection',450,E'{"planningOrder":450,"planningEnabled":false,"scheduleEnabled":false,"batchEnabled":false,"shortCode":"ST_FINAL","color":"#475569","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'REWORK',E'ST Rework',460,E'{"planningOrder":460,"planningEnabled":false,"scheduleEnabled":false,"batchEnabled":false,"shortCode":"REWORK","color":"#B45309","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'CCNV_MANUAL',E'Chemical Conversion - Manual/Generic',470,E'{"planningOrder":470,"planningEnabled":true,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"CCNV_MAN","color":"#0F766E","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'PAINT_POWDER',E'Paint Powder',480,E'{"planningOrder":480,"planningEnabled":false,"scheduleEnabled":true,"batchEnabled":true,"shortCode":"PAINT_PO","color":"#C026D3","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'NON_ST',E'Non-ST / Other Operation',490,E'{"planningOrder":490,"planningEnabled":false,"scheduleEnabled":false,"batchEnabled":false,"shortCode":"NON_ST","color":"#64748B","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb),
(E'MAIN_OPERATION',E'ST_REVIEW',E'ST Review / Unclassified',500,E'{"planningOrder":500,"planningEnabled":false,"scheduleEnabled":false,"batchEnabled":false,"shortCode":"ST_REVIE","color":"#DC2626","sourceBasis":"Derived from route/resource/support operation evidence","seedVersion":"v012","needsReview":true}'::jsonb)
ON CONFLICT (category,code) DO NOTHING;

INSERT INTO config_items (category,code,label,sort_order,data) VALUES
(E'ST_GROUP',E'CHEMICAL_LINE',E'Chemical Line',10,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'AUTO_SHOT_PEENING',E'Automatic Shot Peening',20,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'MANUAL_SHOT_PEENING',E'Manual Shot Peening',30,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'PASSIVATION',E'Passivation / Brightening',40,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'MASKING',E'Masking / Unmasking',50,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'SIRIUS_CLEANING',E'Sirius Cleaning',60,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'AUTO_BLASTING',E'Automatic Blasting',70,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'MANUAL_BLASTING',E'Manual Blasting',80,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'HE_BAKE',E'He-Bake',90,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'PLATING',E'Plating',100,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'PAINTING',E'Painting',110,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'NDT_INSPECTION',E'NDT / ST Inspection',120,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'REWORK',E'Rework',130,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'NON_ST',E'Non-ST',900,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'ST_GROUP',E'REVIEW',E'Review',990,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb)
ON CONFLICT (category,code) DO NOTHING;

INSERT INTO config_items (category,code,label,sort_order,data) VALUES
(E'PHYSICAL_AREA',E'CHEMICAL_LINE',E'Chemical Line',10,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'AUTO_SHOT_PEENING',E'Automatic Shot Peening',20,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'MANUAL_SHOT_PEENING',E'Manual Shot Peening',30,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'PASSIVATION',E'Passivation / Brightening',40,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'MASKING',E'Masking',50,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'SIRIUS_CLEANING',E'Sirius Cleaning',60,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'AUTO_BLASTING',E'Auto Blasting',70,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'MANUAL_BLASTING',E'Manual Blasting',80,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'HE_BAKE',E'He-Bake Oven',90,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'PLATING',E'Plating',100,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'PAINTING',E'Painting',110,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'NDT_INSPECTION',E'NDT / Inspection',120,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'REWORK',E'Rework Area',130,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'NON_ST',E'Non-ST Area',900,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'PHYSICAL_AREA',E'REVIEW',E'Review / Unassigned',990,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb)
ON CONFLICT (category,code) DO NOTHING;

INSERT INTO config_items (category,code,label,sort_order,data) VALUES
(E'SCHEDULE_AREA',E'CHEMICAL_LINE',E'Chemical Line / Flybar',10,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'AUTO_SHP',E'Auto SHP',20,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'MANUAL_SP',E'Manual SP',30,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'PASSIVATION',E'Passivation',40,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'MASKING',E'Masking',50,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'SPX_CLEAN',E'SPX Clean',60,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'AUTO_DBL',E'Auto DBL',70,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'MANUAL_DBL',E'Manual DBL',80,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'HE_BAKE',E'He-Bake',90,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'PLATING',E'Plating',100,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'PAINTING',E'Painting / Cabins',110,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'NDT',E'NDT / Inspection',120,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'REWORK',E'Rework',130,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'NON_ST',E'Non-ST',900,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb),
(E'SCHEDULE_AREA',E'REVIEW',E'Review / Unassigned',990,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":false}'::jsonb)
ON CONFLICT (category,code) DO NOTHING;

INSERT INTO config_items (category,code,label,sort_order,data) VALUES
(E'PLANNER',E'CHEMICAL_PLANNER',E'Chemical Line Planner (Review)',10,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'SHOT_PEENING_PLANNER',E'Shot Peening Planner (Review)',20,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'PASSIVATION_PLANNER',E'Passivation Planner (Review)',30,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'MASKING_PLANNER',E'Masking Planner (Review)',40,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'CLEANING_PLANNER',E'Sirius Cleaning Planner (Review)',50,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'BLASTING_PLANNER',E'Blasting Planner (Review)',60,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'HE_BAKE_PLANNER',E'He-Bake Planner (Review)',70,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'PLATING_PLANNER',E'Plating Planner (Review)',80,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'PAINTING_PLANNER',E'Painting Planner (Review)',90,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'NDT_PLANNER',E'NDT / Inspection Planner (Review)',100,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'REWORK_PLANNER',E'Rework Planner (Review)',110,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'NON_ST_OWNER',E'Non-ST Owner (Review)',900,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb),
(E'PLANNER',E'CONFIG_REVIEW',E'Configuration Review Owner',990,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lanes + ST source grouping","needsReview":true,"placeholder":true}'::jsonb)
ON CONFLICT (category,code) DO NOTHING;

INSERT INTO config_settings (setting_key,category,label,data_type,value_json,description) VALUES
('seed.v012.applied','PLANNING_MODEL','v012 seeded configuration applied','boolean','true'::jsonb,'Source-driven hierarchy and operation mappings seeded for review.'),
('planningModel.requireHierarchyForPlanning','PLANNING_MODEL','Require hierarchy for Planning','boolean','false'::jsonb,'Kept false until seeded hierarchy is reviewed.')
ON CONFLICT (setting_key) DO UPDATE SET value_json=EXCLUDED.value_json, updated_at=now();
