INSERT INTO config_links (link_type,from_category,from_code,to_category,to_code,sort_order,data) VALUES
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'CMSA',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'CHEMMILL',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'CPBILP',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'CPBILP_A',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PIONBL',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'DE_ANODIZING',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'V_A_SHPN',E'ST_GROUP',E'AUTO_SHOT_PEENING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'MANUALSP',E'ST_GROUP',E'MANUAL_SHOT_PEENING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'CLASP',E'ST_GROUP',E'MANUAL_SHOT_PEENING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'BSAUNSLD',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'TSAUNSLD',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'BSASLD',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'TSASLD',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'CCNV_IM',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'CCNV_IA',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'ANOD_CCNV_FB',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PASS_BRTG',E'ST_GROUP',E'PASSIVATION',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'FMSKG_CM',E'ST_GROUP',E'MASKING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'SIPC',E'ST_GROUP',E'SIRIUS_CLEANING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'SI_SEAL',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'STRIP',E'ST_GROUP',E'PLATING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'STRIP_HE_BAKE',E'ST_GROUP',E'HE_BAKE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'HE_BAKE_M_DBLST',E'ST_GROUP',E'HE_BAKE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'A_DBLST',E'ST_GROUP',E'AUTO_BLASTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'M_DBLST',E'ST_GROUP',E'MANUAL_BLASTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PLA_ZINI',E'ST_GROUP',E'PLATING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PLA_ZINI_HE_BAKE',E'ST_GROUP',E'HE_BAKE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PLA_CC',E'ST_GROUP',E'PLATING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PRIMER',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PRIMER2',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PRIMER3',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'TOPCOAT1',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'TOPCOAT2',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'ANTI_ABRASION',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PAINT_MARKING',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'VARNISH',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'MASKING',E'ST_GROUP',E'MASKING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'UNMASKING',E'ST_GROUP',E'MASKING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'HE_BAKE',E'ST_GROUP',E'HE_BAKE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'NDT',E'ST_GROUP',E'NDT_INSPECTION',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'ST_INSPECTION',E'ST_GROUP',E'NDT_INSPECTION',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'ST_FINAL',E'ST_GROUP',E'NDT_INSPECTION',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'REWORK',E'ST_GROUP',E'REWORK',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'CCNV_MANUAL',E'ST_GROUP',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'PAINT_POWDER',E'ST_GROUP',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'NON_ST',E'ST_GROUP',E'NON_ST',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb),
(E'MAIN_TO_ST_GROUP',E'MAIN_OPERATION',E'ST_REVIEW',E'ST_GROUP',E'REVIEW',0,E'{"seedVersion":"v012","sourceBasis":"inferred hierarchy","needsReview":true}'::jsonb)
ON CONFLICT (link_type,from_category,from_code,to_category,to_code) DO NOTHING;

INSERT INTO config_links (link_type,from_category,from_code,to_category,to_code,sort_order,data) VALUES
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'CHEMICAL_LINE',E'PHYSICAL_AREA',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'AUTO_SHOT_PEENING',E'PHYSICAL_AREA',E'AUTO_SHOT_PEENING',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'MANUAL_SHOT_PEENING',E'PHYSICAL_AREA',E'MANUAL_SHOT_PEENING',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'PASSIVATION',E'PHYSICAL_AREA',E'PASSIVATION',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'MASKING',E'PHYSICAL_AREA',E'MASKING',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'SIRIUS_CLEANING',E'PHYSICAL_AREA',E'SIRIUS_CLEANING',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'AUTO_BLASTING',E'PHYSICAL_AREA',E'AUTO_BLASTING',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'MANUAL_BLASTING',E'PHYSICAL_AREA',E'MANUAL_BLASTING',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'HE_BAKE',E'PHYSICAL_AREA',E'HE_BAKE',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'PLATING',E'PHYSICAL_AREA',E'PLATING',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'PAINTING',E'PHYSICAL_AREA',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'NDT_INSPECTION',E'PHYSICAL_AREA',E'NDT_INSPECTION',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'REWORK',E'PHYSICAL_AREA',E'REWORK',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'NON_ST',E'PHYSICAL_AREA',E'NON_ST',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb),
(E'ST_GROUP_TO_PHYSICAL_AREA',E'ST_GROUP',E'REVIEW',E'PHYSICAL_AREA',E'REVIEW',0,E'{"seedVersion":"v012","sourceBasis":"area inferred from source/resources","needsReview":true}'::jsonb)
ON CONFLICT (link_type,from_category,from_code,to_category,to_code) DO NOTHING;

INSERT INTO config_links (link_type,from_category,from_code,to_category,to_code,sort_order,data) VALUES
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'CHEMICAL_LINE',E'SCHEDULE_AREA',E'CHEMICAL_LINE',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'AUTO_SHOT_PEENING',E'SCHEDULE_AREA',E'AUTO_SHP',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'MANUAL_SHOT_PEENING',E'SCHEDULE_AREA',E'MANUAL_SP',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'PASSIVATION',E'SCHEDULE_AREA',E'PASSIVATION',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'MASKING',E'SCHEDULE_AREA',E'MASKING',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'SIRIUS_CLEANING',E'SCHEDULE_AREA',E'SPX_CLEAN',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'AUTO_BLASTING',E'SCHEDULE_AREA',E'AUTO_DBL',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'MANUAL_BLASTING',E'SCHEDULE_AREA',E'MANUAL_DBL',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'HE_BAKE',E'SCHEDULE_AREA',E'HE_BAKE',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'PLATING',E'SCHEDULE_AREA',E'PLATING',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'PAINTING',E'SCHEDULE_AREA',E'PAINTING',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'NDT_INSPECTION',E'SCHEDULE_AREA',E'NDT',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'REWORK',E'SCHEDULE_AREA',E'REWORK',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'NON_ST',E'SCHEDULE_AREA',E'NON_ST',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb),
(E'PHYSICAL_TO_SCHEDULE_AREA',E'PHYSICAL_AREA',E'REVIEW',E'SCHEDULE_AREA',E'REVIEW',0,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane alignment","needsReview":true}'::jsonb)
ON CONFLICT (link_type,from_category,from_code,to_category,to_code) DO NOTHING;

INSERT INTO config_links (link_type,from_category,from_code,to_category,to_code,sort_order,data) VALUES
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'CHEMICAL_LINE',E'PLANNER',E'CHEMICAL_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'AUTO_SHP',E'PLANNER',E'SHOT_PEENING_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'MANUAL_SP',E'PLANNER',E'SHOT_PEENING_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'PASSIVATION',E'PLANNER',E'PASSIVATION_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'MASKING',E'PLANNER',E'MASKING_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'SPX_CLEAN',E'PLANNER',E'CLEANING_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'AUTO_DBL',E'PLANNER',E'BLASTING_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'MANUAL_DBL',E'PLANNER',E'BLASTING_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'HE_BAKE',E'PLANNER',E'HE_BAKE_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'PLATING',E'PLANNER',E'PLATING_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'PAINTING',E'PLANNER',E'PAINTING_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'NDT',E'PLANNER',E'NDT_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'REWORK',E'PLANNER',E'REWORK_PLANNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'NON_ST',E'PLANNER',E'NON_ST_OWNER',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb),
(E'SCHEDULE_AREA_TO_PLANNER',E'SCHEDULE_AREA',E'REVIEW',E'PLANNER',E'CONFIG_REVIEW',0,E'{"seedVersion":"v012","sourceBasis":"placeholder role assignment","needsReview":true,"placeholder":true}'::jsonb)
ON CONFLICT (link_type,from_category,from_code,to_category,to_code) DO NOTHING;

INSERT INTO config_links (link_type,from_category,from_code,to_category,to_code,sort_order,data) VALUES
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'CMSA',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'CHEMMILL',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'CPBILP',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'CPBILP_A',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PIONBL',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'DE_ANODIZING',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'BSAUNSLD',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'TSAUNSLD',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'BSASLD',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'TSASLD',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'CCNV_IM',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'CCNV_IA',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'ANOD_CCNV_FB',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'SI_SEAL',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'CCNV_MANUAL',E'RESOURCE',E'FLYBAR',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'V_A_SHPN',E'RESOURCE',E'AUTO_SHP',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'MANUALSP',E'RESOURCE',E'MANUAL_SP',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'CLASP',E'RESOURCE',E'MANUAL_SP',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PASS_BRTG',E'RESOURCE',E'PASSIVATION',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'SIPC',E'RESOURCE',E'SPX_CLEAN',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'A_DBLST',E'RESOURCE',E'AUTO_DBL',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'M_DBLST',E'RESOURCE',E'MANUAL_DBL',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'STRIP',E'RESOURCE',E'PLATING',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PLA_ZINI',E'RESOURCE',E'PLATING',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PLA_CC',E'RESOURCE',E'PLATING',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'STRIP_HE_BAKE',E'RESOURCE',E'HE_BAKE',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'HE_BAKE_M_DBLST',E'RESOURCE',E'HE_BAKE',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PLA_ZINI_HE_BAKE',E'RESOURCE',E'HE_BAKE',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'HE_BAKE',E'RESOURCE',E'HE_BAKE',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER',E'RESOURCE',E'CAB1',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER',E'RESOURCE',E'CAB2',2,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER',E'RESOURCE',E'CAB3',3,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER2',E'RESOURCE',E'CAB1',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER2',E'RESOURCE',E'CAB2',2,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER2',E'RESOURCE',E'CAB3',3,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER3',E'RESOURCE',E'CAB1',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER3',E'RESOURCE',E'CAB2',2,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PRIMER3',E'RESOURCE',E'CAB3',3,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'TOPCOAT1',E'RESOURCE',E'CAB1',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'TOPCOAT1',E'RESOURCE',E'CAB2',2,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'TOPCOAT1',E'RESOURCE',E'CAB3',3,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'TOPCOAT2',E'RESOURCE',E'CAB1',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'TOPCOAT2',E'RESOURCE',E'CAB2',2,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'TOPCOAT2',E'RESOURCE',E'CAB3',3,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'ANTI_ABRASION',E'RESOURCE',E'CAB1',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'ANTI_ABRASION',E'RESOURCE',E'CAB2',2,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'ANTI_ABRASION',E'RESOURCE',E'CAB3',3,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PAINT_MARKING',E'RESOURCE',E'CAB1',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PAINT_MARKING',E'RESOURCE',E'CAB2',2,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PAINT_MARKING',E'RESOURCE',E'CAB3',3,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'VARNISH',E'RESOURCE',E'CAB1',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'VARNISH',E'RESOURCE',E'CAB2',2,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'VARNISH',E'RESOURCE',E'CAB3',3,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":true}'::jsonb),
(E'MAIN_TO_RESOURCE',E'MAIN_OPERATION',E'PAINT_POWDER',E'RESOURCE',E'PAINT_POWDER',1,E'{"seedVersion":"v012","sourceBasis":"Main Planning resource lane","needsReview":false}'::jsonb)
ON CONFLICT (link_type,from_category,from_code,to_category,to_code) DO NOTHING;
