-- ST Planning v013 Recipe Rule seed
-- 1 statement. Rules are source-driven and editable in CFG-92.

INSERT INTO config_rules (rule_type, code, name, enabled, priority, condition_json, action_json, notes)
VALUES
('RECIPE','CMSA_STATIC_004','CMSA → Surface activation recipe 4',true,10,'{"mainOperation":"CMSA"}'::jsonb,'{"selector":"STATIC_CODE","recipeNo":"4","confidence":"MEDIUM","needsReview":true}'::jsonb,'STRecipe names Recipe 4 as Surface activation for chemical milling, seeded by name match, review before production use.'),
('RECIPE','CHEMMILL_STATIC_005','CHEMMILL → Chemical Milling recipe 5',true,10,'{"mainOperation":"CHEMMILL"}'::jsonb,'{"selector":"STATIC_CODE","recipeNo":"5","confidence":"MEDIUM","needsReview":true}'::jsonb,'STRecipe names Recipe 5 as Chemical Milling, seeded by name match.'),
('RECIPE','CPBILP_PRE_SURFACE','CPBILP recipe from AddInfo_Pre&Surface',true,10,'{"mainOperation":"CPBILP"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_PRE_SURFACE"]}'::jsonb,'Source recipe number field AddInfo_Pre&Surface.'),
('RECIPE','CPBILP_A_PRE_SURFACE','CPBILP-A recipe from AddInfo_Pre&Surface',true,10,'{"mainOperation":"CPBILP_A"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_PRE_SURFACE"]}'::jsonb,'Source recipe number field AddInfo_Pre&Surface.'),
('RECIPE','DE_ANOD_STATIC_007','De-Anodizing → Recipe 7',true,10,'{"mainOperation":"DE_ANODIZING"}'::jsonb,'{"selector":"STATIC_CODE","recipeNo":"7","confidence":"HIGH"}'::jsonb,'STRecipe names Recipe 7 as Deanodizing.'),
('RECIPE','BSAUNSLD_ANOD','BSA Unsealed recipe from anodizing source',true,10,'{"mainOperation":"BSAUNSLD"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_ANODIZING"]}'::jsonb,'AddInfo_.Anodizing Aluminium.'),
('RECIPE','TSAUNSLD_ANOD','TSA Unsealed recipe from anodizing source',true,10,'{"mainOperation":"TSAUNSLD"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_ANODIZING"]}'::jsonb,'AddInfo_.Anodizing Aluminium.'),
('RECIPE','BSASLD_ANOD','BSA Sealed recipe from anodizing source',true,10,'{"mainOperation":"BSASLD"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_ANODIZING"]}'::jsonb,'AddInfo_.Anodizing Aluminium.'),
('RECIPE','TSASLD_ANOD','TSA Sealed recipe from anodizing source',true,10,'{"mainOperation":"TSASLD"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_ANODIZING"]}'::jsonb,'AddInfo_.Anodizing Aluminium.'),
('RECIPE','CCNV_IM_ANOD','CCNV-IM recipe from anodizing source',true,10,'{"mainOperation":"CCNV_IM"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_ANODIZING"]}'::jsonb,'AddInfo_.Anodizing Aluminium.'),
('RECIPE','CCNV_IA_ANOD','CCNV-IA recipe from anodizing source',true,10,'{"mainOperation":"CCNV_IA"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_ANODIZING"]}'::jsonb,'AddInfo_.Anodizing Aluminium.'),
('RECIPE','ANOD_CCNV_FB_ANOD','ANOD/CCNV Flybar recipe from anodizing source',true,10,'{"mainOperation":"ANOD_CCNV_FB"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_ANODIZING"]}'::jsonb,'AddInfo_.Anodizing Aluminium.'),
('RECIPE','PASS_BRTG_PA','Passivation / Brightening recipe from PA source when present',true,10,'{"mainOperation":"PASS_BRTG"}'::jsonb,'{"selector":"SOURCE_CODE","allowedPrefixes":["PA-"],"ignoreValues":["N/A"],"confidence":"MEDIUM","needsReview":true,"sourceFields":["ADD_PRE_SURFACE"]}'::jsonb,'Only PA-* values from AddInfo_Pre&Surface are accepted, source does not provide a dedicated Passivation recipe column.'),
('RECIPE','SIPC_SIRIUS','SIPC recipe from Sirius_cleaning.Recipe',true,10,'{"mainOperation":"SIPC"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["SIRIUS_RECIPE_NO"]}'::jsonb,'Direct source recipe field.'),
('RECIPE','SI_SEAL_SIRIUS','SI Seal recipe from Sirius_cleaning.Recipe',true,10,'{"mainOperation":"SI_SEAL"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"MEDIUM","needsReview":true,"sourceFields":["SIRIUS_RECIPE_NO"]}'::jsonb,'Observed source recipe available on SI Seal rows.'),
('RECIPE','AUTO_SHP_PVT','Auto Shot Peening recipe PVT',true,10,'{"mainOperation":"V_A_SHPN"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"allowUncatalogued":true,"confidence":"HIGH","sourceFields":["AUTO_SHP_RECIPE_PVT"]}'::jsonb,'AutoSP.1.RECIPE PVT is the source recipe identifier.'),
('RECIPE','MANUAL_SP_EXEC','Manual Shot Peening execution file',true,10,'{"mainOperation":"MANUALSP"}'::jsonb,'{"selector":"SOURCE_IDENTIFIER","identifierType":"EXECUTION_FILE","confidence":"HIGH","sourceFields":["MANUAL_SP_EXECUTION_FILE"]}'::jsonb,'Source does not expose a Recipe No. for Manual Shot Peening, execution file is retained without inventing a recipe number.'),
('RECIPE','STRIP_STATIC_ZNNI03','Strip → ZnNi-03',true,10,'{"mainOperation":"STRIP"}'::jsonb,'{"selector":"STATIC_CODE","recipeNo":"ZnNi-03","confidence":"MEDIUM","needsReview":true}'::jsonb,'STRecipe labels ZnNi-03 as Stripping, review before production use.'),
('RECIPE','STRIP_HE_BAKE_SOURCE','Strip + He-Bake recipe from Hebake Recipe after Strip',true,10,'{"mainOperation":"STRIP_HE_BAKE"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["HE_AFTER_STRIP"]}'::jsonb,'Hebake Recipe after Strip.'),
('RECIPE','HE_BAKE_BEFORE_BLAST','He-Bake before blasting recipe',true,10,'{"mainOperation":"HE_BAKE_M_DBLST"}'::jsonb,'{"selector":"SOURCE_CODE_LIST","splitPattern":"\\s*/\\s*[\\r\\n]*\\s*","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["HE_BEFORE_BLASTING"]}'::jsonb,'Before Blasting can contain multiple recipe codes such as HE-05 / HE-01.'),
('RECIPE','PLA_ZINI_PLATING','ZnNi Plating recipe',true,10,'{"mainOperation":"PLA_ZINI"}'::jsonb,'{"selector":"FIRST_SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["PLATING_LINE_RECIPE","PLATING_RECIPE_NO"]}'::jsonb,'Prefer PlatingLine.Plating, fallback Plating_recipe.'),
('RECIPE','PLA_ZINI_HE_BAKE','ZnNi + He-Bake primary recipe',true,10,'{"mainOperation":"PLA_ZINI_HE_BAKE"}'::jsonb,'{"selector":"FIRST_SOURCE_CODE","ignoreValues":["N/A"],"confidence":"MEDIUM","needsReview":true,"sourceFields":["PLATING_LINE_RECIPE","PLATING_RECIPE_NO"],"secondarySourceFields":["HE_AFTER_PLATING"]}'::jsonb,'Combined main operation can have plating + bake recipes, primary suggestion is plating, secondary source retained.'),
('RECIPE','PLA_CC_CHROMATE','Plating / Chromate recipe',true,10,'{"mainOperation":"PLA_CC"}'::jsonb,'{"selector":"FIRST_SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["CHROMATE_RECIPE","PLATING_LINE_RECIPE"]}'::jsonb,'Prefer Chromate Coating recipe, fallback plating recipe.'),
('RECIPE','HE_BAKE_GENERIC','Generic He-Bake recipe from source context',true,20,'{"mainOperation":"HE_BAKE"}'::jsonb,'{"selector":"FIRST_SOURCE_CODE","ignoreValues":["N/A"],"confidence":"MEDIUM","needsReview":true,"sourceFields":["HE_AFTER_PLATING","HE_AFTER_PLATING_PARAM","HE_AFTER_STRIP_PARAM","HE_AFTER_CC","HE_BEFORE_BLASTING","HE_AFTER_STRIP"]}'::jsonb,'Multiple context-specific HE-BAKE columns exist, source priority is configurable and should be reviewed.'),
('RECIPE','FLUID_MASKANT','Fluid Masking recipe from source name',true,10,'{"mainOperation":"FMSKG_CM"}'::jsonb,'{"selector":"SOURCE_NAME","fallbackRecipeNo":"100","confidence":"HIGH","sourceFields":["FLUID_MASKING_NAME"]}'::jsonb,'Source Part_Masterlist.FluidMasking uses Fluid Maskant, STRecipe Recipe 100.'),
('RECIPE','PRIMER1_CODE','Primer 1 recipe number',true,10,'{"mainOperation":"PRIMER"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_PRIMER1"]}'::jsonb,'AddInfo_Primer 1.'),
('RECIPE','PRIMER2_NAME','Primer 2 recipe from source material name',true,10,'{"mainOperation":"PRIMER2"}'::jsonb,'{"selector":"SOURCE_NAME","confidence":"HIGH","sourceFields":["PRIMER2_NAME"]}'::jsonb,'Part_Masterlist.PRIMER2, lookup by Recipe Master name/alias.'),
('RECIPE','PRIMER3_NAME','Primer 3 recipe from source material name',true,10,'{"mainOperation":"PRIMER3"}'::jsonb,'{"selector":"SOURCE_NAME","confidence":"HIGH","sourceFields":["PRIMER3_NAME"]}'::jsonb,'Part_Masterlist.PRIMER3, lookup by Recipe Master name/alias.'),
('RECIPE','TOPCOAT1_CODE','Topcoat 1 recipe number',true,10,'{"mainOperation":"TOPCOAT1"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_TOPCOAT"]}'::jsonb,'AddInfo_Top Coat.'),
('RECIPE','TOPCOAT2_NAME','Topcoat 2 recipe from source material name',true,10,'{"mainOperation":"TOPCOAT2"}'::jsonb,'{"selector":"SOURCE_NAME","confidence":"HIGH","sourceFields":["TOPCOAT2_NAME"]}'::jsonb,'Part_Masterlist.TOPCOAT2, lookup by Recipe Master name/alias.'),
('RECIPE','ANTI_ABRASION_CODE','Anti-Abrasion recipe number',true,10,'{"mainOperation":"ANTI_ABRASION"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_ANTIABRASION"]}'::jsonb,'AddInfo_Anti Abrasion Paint.'),
('RECIPE','VARNISH_CODE','Varnish / Clear Coat recipe number',true,10,'{"mainOperation":"VARNISH"}'::jsonb,'{"selector":"SOURCE_CODE","ignoreValues":["N/A"],"confidence":"HIGH","sourceFields":["ADD_CLEARCOAT"]}'::jsonb,'AddInfo_Clear Coat.')
ON CONFLICT (rule_type, code) DO NOTHING;
