-- ST Planning v013 Process Time Rule seed
-- 1 statement.
-- Rules with unconfirmed source units/calculation behavior are intentionally seeded DISABLED + needsReview.

INSERT INTO config_rules (rule_type, code, name, enabled, priority, condition_json, action_json, notes)
VALUES
('PROCESS_TIME','RECIPE_DEFAULT_TIME','Use Recipe Master default process time',true,100,'{"recipeDefaultProcessTimePresent":true}'::jsonb,'{"profile":"RECIPE_DEFAULT_FIXED","mode":"RECIPE_DEFAULT_MINUTES","rounding":"SETTING"}'::jsonb,'Directly derived from STRecipe Duration when numeric.'),
('PROCESS_TIME','BLASTING_SOURCE_TIME','Blasting time from source minutes',true,10,'{"mainOperationIn":["A_DBLST","M_DBLST"]}'::jsonb,'{"profile":"BLASTING_SOURCE_MINUTES","mode":"SOURCE_COLUMN","unit":"MINUTE","sourceField":"BLASTING_TIME","batchSizeField":"BLASTING_BATCH_SIZE"}'::jsonb,'Header explicitly states Blasting time (minute).'),
('PROCESS_TIME','SIRIUS_QTY_TIME','Sirius cleaning time by source quantity breakpoints',false,10,'{"mainOperation":"SIPC"}'::jsonb,'{"profile":"SIRIUS_QTY_BREAKPOINTS","mode":"SOURCE_QTY_BREAKPOINTS","qtyField":"prodQty","breakpoints":[{"qty":10,"sourceField":"SIRIUS_TIME_10"},{"qty":20,"sourceField":"SIRIUS_TIME_20"},{"qty":50,"sourceField":"SIRIUS_TIME_50"}],"operators":2,"unit":"MINUTE","needsReview":true,"batchSizeField":"SIRIUS_BATCH_SIZE"}'::jsonb,'Source provides 10/20/50-pcs times but does not define interpolation/rounding behavior, disabled until user confirms the calculation rule.'),
('PROCESS_TIME','MASK_SOURCE_CU','Masking/marking source time · V_MRK-DP',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_CU"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"V_MRK-DP","needsReview":true,"sourceField":"MASK_CU"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_CV','Masking/marking source time · MRKG-LA',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_CV"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MRKG-LA","needsReview":true,"sourceField":"MASK_CV"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_CW','Masking/marking source time · MSKG-PC',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_CW"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKG-PC","needsReview":true,"sourceField":"MASK_CW"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_CX','Masking/marking source time · UNMSKG after Precleaning',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_CX"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"UNMSKG after Precleaning","needsReview":true,"sourceField":"MASK_CX"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_CY','Masking/marking source time · MSKG-DBL',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_CY"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKG-DBL","needsReview":true,"sourceField":"MASK_CY"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_CZ','Masking/marking source time · MSKG-SP',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_CZ"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKG-SP","needsReview":true,"sourceField":"MASK_CZ"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DA','Masking/marking source time · UNMSKG-S',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DA"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"UNMSKG-S","needsReview":true,"sourceField":"MASK_DA"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DB','Masking/marking source time · MSKG-MEC',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DB"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKG-MEC","needsReview":true,"sourceField":"MASK_DB"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DC','Masking/marking source time · MSKAFSHP',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DC"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKAFSHP","needsReview":true,"sourceField":"MASK_DC"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DD','Masking/marking source time · UNMSKG',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DD"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"UNMSKG","needsReview":true,"sourceField":"MASK_DD"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DE','Masking/marking source time · MSKG-AND',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DE"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKG-AND","needsReview":true,"sourceField":"MASK_DE"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DF','Masking/marking source time · V_MSKBCC',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DF"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"V_MSKBCC","needsReview":true,"sourceField":"MASK_DF"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DG','Masking/marking source time · MSKG-TC (before primer)',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DG"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKG-TC (before primer)","needsReview":true,"sourceField":"MASK_DG"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DH','Masking/marking source time · UNMSKG after Primer1',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DH"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"UNMSKG after Primer1","needsReview":true,"sourceField":"MASK_DH"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DI','Masking/marking source time · MSKG-TC (before primer2)',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DI"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKG-TC (before primer2)","needsReview":true,"sourceField":"MASK_DI"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DJ','Masking/marking source time · MSKG-TC (before topcoat1)',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DJ"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKG-TC (before topcoat1)","needsReview":true,"sourceField":"MASK_DJ"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DK','Masking/marking source time · MSKGABP',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DK"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"MSKGABP","needsReview":true,"sourceField":"MASK_DK"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DL','Masking/marking source time · UNMSKG _1',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DL"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"UNMSKG _1","needsReview":true,"sourceField":"MASK_DL"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DM','Masking/marking source time · V_MSKBCC _2',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DM"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"V_MSKBCC _2","needsReview":true,"sourceField":"MASK_DM"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.'),
('PROCESS_TIME','MASK_SOURCE_DN','Masking/marking source time · UNMSKG _3',false,20,'{"mainOperationIn":["MASKING","UNMASKING","PAINT_MARKING"],"sourceField":"MASK_DN"}'::jsonb,'{"profile":"MASKING_SOURCE_VALUES","mode":"SOURCE_COLUMN","unit":"SOURCE_UNCONFIRMED","sourceHeader":"UNMSKG _3","needsReview":true,"sourceField":"MASK_DN"}'::jsonb,'Source contains numeric process-time values but the unit is not stated in the supplied header. Disabled until unit/usage is confirmed.')
ON CONFLICT (rule_type, code) DO NOTHING;
