-- ST Planning v017 — Batch Capacity Baseline
-- 1. Enable masking/unmasking/support route steps for internal finite-capacity batching.
UPDATE config_items
SET data = data || '{"scheduleEnabled":true,"batchEnabled":true,"seedVersion":"v017","assumptionBaseline":true}'::jsonb, updated_at=now()
WHERE category='MAIN_OPERATION' AND code = ANY(ARRAY['MASKING','UNMASKING','NDT','ST_INSPECTION','ST_FINAL','REWORK']);

UPDATE config_rules
SET action_json = action_json || '{"maxJobs":20,"maxQty":1000,"maxSurfaceDm2":10000}'::jsonb,
    notes='v017 global safety fallback: 20 jobs / 1000 pcs / 10000 dm2. Lower-priority-number Main Operation rules override.', updated_at=now()
WHERE rule_type='BATCH' AND code='DEFAULT_BATCH';

INSERT INTO config_rules (rule_type,code,name,enabled,priority,condition_json,action_json,notes) VALUES
(E'BATCH',E'CHEM_BATCH_CAP',E'Chemical Line batch capacity',true,100,E'{"mainOperationIn":["CMSA","CHEMMILL","CPBILP","CPBILP_A","PIONBL","DE_ANODIZING","BSAUNSLD","TSAUNSLD","BSASLD","TSASLD","CCNV_IM","CCNV_IA","ANOD_CCNV_FB","SI_SEAL","CCNV_MANUAL"]}'::jsonb,E'{"keyFields":["MAIN_OPERATION","RECIPE_NO"],"delimiter":"|","maxJobs":20,"maxQty":1000,"maxSurfaceDm2":10000,"processTimeAggregation":"MAX","requireRecipe":false}'::jsonb,E'v017 baseline capacity for one flybar batch.'),
(E'BATCH',E'PAINT_BATCH_CAP',E'Painting batch capacity',true,100,E'{"mainOperationIn":["PRIMER","PRIMER2","PRIMER3","TOPCOAT1","TOPCOAT2","ANTI_ABRASION","VARNISH"]}'::jsonb,E'{"keyFields":["MAIN_OPERATION","RECIPE_NO"],"delimiter":"|","maxJobs":20,"maxQty":1500,"maxSurfaceDm2":10000,"processTimeAggregation":"MAX","requireRecipe":false}'::jsonb,E'v017 baseline cabin batch limit.'),
(E'BATCH',E'PAINT_MARK_BATCH_CAP',E'Paint marking batch capacity',true,90,E'{"mainOperation":"PAINT_MARKING"}'::jsonb,E'{"keyFields":["MAIN_OPERATION","NEXT_OPERATION","PROGRAM"],"delimiter":"|","maxJobs":10,"maxQty":300,"maxSurfaceDm2":5000,"processTimeAggregation":"SUM"}'::jsonb,E'Manual marking modeled as serial work inside a resource slot.'),
(E'BATCH',E'MASK_BATCH_CAP',E'Masking batch capacity',true,80,E'{"mainOperationIn":["MASKING","FMSKG_CM"]}'::jsonb,E'{"keyFields":["MAIN_OPERATION","NEXT_OPERATION","PART_CLUSTER"],"delimiter":"|","maxJobs":8,"maxQty":250,"maxSurfaceDm2":5000,"processTimeAggregation":"SUM"}'::jsonb,E'Manual masking serial duration; multiple masking stations provide parallel capacity.'),
(E'BATCH',E'UNMASK_BATCH_CAP',E'Unmasking batch capacity',true,80,E'{"mainOperation":"UNMASKING"}'::jsonb,E'{"keyFields":["MAIN_OPERATION","NEXT_OPERATION","PART_CLUSTER"],"delimiter":"|","maxJobs":10,"maxQty":400,"maxSurfaceDm2":7000,"processTimeAggregation":"SUM"}'::jsonb,E'Manual unmasking serial duration; multiple stations provide parallel capacity.'),
(E'BATCH',E'SHOT_BATCH_CAP',E'Shot peening batch capacity',true,100,E'{"mainOperationIn":["V_A_SHPN","MANUALSP","CLASP"]}'::jsonb,E'{"keyFields":["MAIN_OPERATION","RECIPE_NO","NEXT_OPERATION"],"delimiter":"|","maxJobs":12,"maxQty":500,"maxSurfaceDm2":7000,"processTimeAggregation":"MAX"}'::jsonb,E'v017 shot-peening batch baseline.'),
(E'BATCH',E'BLAST_BATCH_CAP',E'Blasting batch capacity',true,100,E'{"mainOperationIn":["A_DBLST","M_DBLST"]}'::jsonb,E'{"keyFields":["MAIN_OPERATION","NEXT_OPERATION"],"delimiter":"|","maxJobs":10,"maxQty":500,"maxSurfaceDm2":8000,"processTimeAggregation":"MAX"}'::jsonb,E'v017 blasting batch baseline; per-job source blasting time already scales by source batch size.'),
(E'BATCH',E'PLATING_BATCH_CAP',E'Plating batch capacity',true,100,E'{"mainOperationIn":["STRIP","PLA_ZINI","PLA_CC"]}'::jsonb,E'{"keyFields":["MAIN_OPERATION","RECIPE_NO"],"delimiter":"|","maxJobs":15,"maxQty":800,"maxSurfaceDm2":8000,"processTimeAggregation":"MAX"}'::jsonb,E'v017 plating batch baseline.'),
(E'BATCH',E'HEBAKE_BATCH_CAP',E'He-Bake batch capacity',true,100,E'{"mainOperationIn":["STRIP_HE_BAKE","HE_BAKE_M_DBLST","PLA_ZINI_HE_BAKE","HE_BAKE"]}'::jsonb,E'{"keyFields":["MAIN_OPERATION","RECIPE_NO"],"delimiter":"|","maxJobs":20,"maxQty":1500,"maxSurfaceDm2":12000,"processTimeAggregation":"MAX"}'::jsonb,E'v017 oven load baseline.'),
(E'BATCH',E'SIRIUS_BATCH_CAP',E'Sirius cleaning batch capacity',true,100,E'{"mainOperation":"SIPC"}'::jsonb,E'{"keyFields":["MAIN_OPERATION","RECIPE_NO"],"delimiter":"|","maxJobs":10,"maxQty":120,"maxSurfaceDm2":4000,"processTimeAggregation":"SUM"}'::jsonb,E'Matches source batch-size field order of magnitude; editable.'),
(E'BATCH',E'PASS_BATCH_CAP',E'Passivation batch capacity',true,100,E'{"mainOperation":"PASS_BRTG"}'::jsonb,E'{"keyFields":["MAIN_OPERATION","RECIPE_NO"],"delimiter":"|","maxJobs":15,"maxQty":800,"maxSurfaceDm2":8000,"processTimeAggregation":"MAX"}'::jsonb,E'v017 passivation baseline.'),
(E'BATCH',E'NDT_INSPECTION_BATCH_CAP',E'NDT / Inspection capacity group',true,100,E'{"mainOperationIn":["NDT","ST_INSPECTION","ST_FINAL"]}'::jsonb,E'{"keyFields":["MAIN_OPERATION","NEXT_OPERATION"],"delimiter":"|","maxJobs":20,"maxQty":1000,"maxSurfaceDm2":12000,"processTimeAggregation":"SUM"}'::jsonb,E'Internal finite-capacity group for route timing. These Main Operations may remain planning-disabled.'),
(E'BATCH',E'REWORK_BATCH_CAP',E'Rework capacity group',true,100,E'{"mainOperation":"REWORK"}'::jsonb,E'{"keyFields":["MAIN_OPERATION","NEXT_OPERATION","PART"],"delimiter":"|","maxJobs":5,"maxQty":150,"maxSurfaceDm2":3000,"processTimeAggregation":"SUM"}'::jsonb,E'Internal finite-capacity rework baseline.'),
(E'BATCH',E'POWDER_BATCH_CAP',E'Powder paint batch capacity',true,100,E'{"mainOperation":"PAINT_POWDER"}'::jsonb,E'{"keyFields":["MAIN_OPERATION","RECIPE_NO"],"delimiter":"|","maxJobs":15,"maxQty":800,"maxSurfaceDm2":8000,"processTimeAggregation":"MAX"}'::jsonb,E'v017 powder-coating line baseline.')
ON CONFLICT (rule_type,code) DO UPDATE SET name=EXCLUDED.name,enabled=true,priority=EXCLUDED.priority,condition_json=EXCLUDED.condition_json,action_json=EXCLUDED.action_json,notes=EXCLUDED.notes,updated_at=now();
