-- ST Planning v020 — Masking / Unmasking manpower + workstation segmented finite-capacity model
-- Run after v019. This file contains 4 statements (Aiven-safe: <= 8).

INSERT INTO config_settings (setting_key,category,label,data_type,value_json,enabled,description) VALUES
('capacity.manualWorkSegmented','CAPACITY_MODEL','Manual Work Segmented Scheduler','boolean','true'::jsonb,true,'Enable detailed Masking / Fluid Masking / Unmasking workstation + labor-pool finite scheduling.'),
('capacity.manualWorkMainOperations','CAPACITY_MODEL','Manual Work Main Operations','json','["MASKING","FMSKG_CM","UNMASKING"]'::jsonb,true,'Main Operations handled by the v020 manual-work scheduler.'),
('capacity.maskingResourceCode','CAPACITY_MODEL','Masking Workstation Resource','string','"MASKING"'::jsonb,true,'Physical workstation resource for Masking and Fluid Masking.'),
('capacity.unmaskingResourceCode','CAPACITY_MODEL','Unmasking Workstation Resource','string','"UNMASKING"'::jsonb,true,'Physical workstation resource for Unmasking.'),
('capacity.maskingLaborResourceCode','CAPACITY_MODEL','Masking Labor Pool','string','"MASKING_LABOR"'::jsonb,true,'Shared operator pool consumed by masking setup/work/release segments.'),
('capacity.unmaskingLaborResourceCode','CAPACITY_MODEL','Unmasking Labor Pool','string','"UNMASKING_LABOR"'::jsonb,true,'Shared operator pool consumed by unmasking setup/work/release segments.'),
('capacity.manualSetupAggregation','CAPACITY_MODEL','Manual Setup Aggregation','string','"MAX_MEMBER"'::jsonb,true,'For a grouped manual batch, use the maximum member setup once. Alternatives supported by engine: SUM_MEMBER or FIXED.'),
('capacity.maskingDefaultSetupMinutes','CAPACITY_MODEL','Masking Default Setup Minutes','number','10'::jsonb,true,'Fallback setup when the selected Process Time rule does not expose setupMinutes.'),
('capacity.unmaskingDefaultSetupMinutes','CAPACITY_MODEL','Unmasking Default Setup Minutes','number','5'::jsonb,true,'Fallback setup for Unmasking.'),
('capacity.manualReleaseMinutes','CAPACITY_MODEL','Manual Release Minutes','number','5'::jsonb,true,'Default closeout/release segment after manual work.'),
('capacity.manualMaxOperatorsPerBatch','CAPACITY_MODEL','Manual Max Operators per Batch','number','2'::jsonb,true,'Default upper limit for operators assigned simultaneously to one masking/unmasking batch.'),
('capacity.manualOperator2ThresholdWorkMinutes','CAPACITY_MODEL','Manual Additional Operator Threshold','number','240'::jsonb,true,'One-operator labor minutes per effective operator target. Example: >240 labor-minutes allows a second operator when capacity exists.'),
('capacity.manualParallelEfficiency','CAPACITY_MODEL','Manual Parallel Efficiency','number','0.85'::jsonb,true,'Efficiency of each additional operator. Two operators at 0.85 give 1.85 effective operators, avoiding perfect linear scaling.')
ON CONFLICT (setting_key) DO UPDATE SET category=EXCLUDED.category,label=EXCLUDED.label,data_type=EXCLUDED.data_type,value_json=EXCLUDED.value_json,enabled=true,description=EXCLUDED.description,updated_at=now();

INSERT INTO config_items (category,code,label,sort_order,data) VALUES
('CAPACITY_RESOURCE','MASKING','Masking Workstation',140,'{"baseResourceCode":"MASKING","instanceCount":4,"instancePrefix":"MSK","maxConcurrent":4,"changeoverMinutes":0,"calendarMode":"CONTINUOUS_24H","segmentedScheduler":true,"segmentOrder":["MANUAL_SETUP","MANUAL_WORK","MANUAL_RELEASE"],"laborResourceCode":"MASKING_LABOR","seedVersion":"v020","assumptionBaseline":true,"sourceBasis":"v017 workstation count + v020 detailed manpower model"}'::jsonb),
('CAPACITY_RESOURCE','UNMASKING','Unmasking Workstation',150,'{"baseResourceCode":"UNMASKING","instanceCount":3,"instancePrefix":"UMS","maxConcurrent":3,"changeoverMinutes":0,"calendarMode":"CONTINUOUS_24H","segmentedScheduler":true,"segmentOrder":["MANUAL_SETUP","MANUAL_WORK","MANUAL_RELEASE"],"laborResourceCode":"UNMASKING_LABOR","seedVersion":"v020","assumptionBaseline":true,"sourceBasis":"v017 workstation count + v020 detailed manpower model"}'::jsonb),
('CAPACITY_RESOURCE','MASKING_LABOR','Masking Operator Pool',145,'{"baseResourceCode":"MASKING_LABOR","instanceCount":1,"instancePrefix":"MOP","maxConcurrent":4,"changeoverMinutes":0,"calendarMode":"CONTINUOUS_24H","capacityUnit":"OPERATOR","seedVersion":"v020","assumptionBaseline":true,"sourceBasis":"user-authorized estimated manpower baseline; editable"}'::jsonb),
('CAPACITY_RESOURCE','UNMASKING_LABOR','Unmasking Operator Pool',155,'{"baseResourceCode":"UNMASKING_LABOR","instanceCount":1,"instancePrefix":"UOP","maxConcurrent":3,"changeoverMinutes":0,"calendarMode":"CONTINUOUS_24H","capacityUnit":"OPERATOR","seedVersion":"v020","assumptionBaseline":true,"sourceBasis":"user-authorized estimated manpower baseline; editable"}'::jsonb)
ON CONFLICT (category,code) DO UPDATE SET label=EXCLUDED.label,sort_order=EXCLUDED.sort_order,data=EXCLUDED.data,enabled=true,updated_at=now();

INSERT INTO config_rules (rule_type,code,name,enabled,priority,condition_json,action_json,notes) VALUES
('MANUAL_CAPACITY','MASK_COMPLEX_TWO_OPERATOR','Complex masking operator baseline',true,10,'{"operationCodeIn":["MSKG-DBL","MSKGABP"]}'::jsonb,'{"allowedResources":["MASKING"],"laborResourceCode":"MASKING_LABOR","parallelAllowed":true,"minOperators":1,"maxOperators":2,"operator2ThresholdWorkMinutes":180,"parallelEfficiency":0.80,"releaseMinutes":5}'::jsonb,'Complex masking operations may use two operators earlier; source min/pc remains the work-content basis.'),
('MANUAL_CAPACITY','FMSKG_CM_MANPOWER','Fluid masking manpower baseline',true,20,'{"mainOperation":"FMSKG_CM"}'::jsonb,'{"allowedResources":["MASKING"],"laborResourceCode":"MASKING_LABOR","parallelAllowed":true,"minOperators":1,"maxOperators":2,"operator2ThresholdWorkMinutes":180,"parallelEfficiency":0.80,"setupMinutes":20,"releaseMinutes":10}'::jsonb,'Fluid masking detailed capacity baseline. Process Time still originates from the v017 min/pc rule.'),
('MANUAL_CAPACITY','MASKING_MANPOWER','Masking manpower baseline',true,30,'{"mainOperation":"MASKING"}'::jsonb,'{"allowedResources":["MASKING"],"laborResourceCode":"MASKING_LABOR","parallelAllowed":true,"minOperators":1,"maxOperators":2,"operator2ThresholdWorkMinutes":240,"parallelEfficiency":0.85,"releaseMinutes":5}'::jsonb,'Default masking rule. Operator allocation is derived from total labor minutes after batch grouping.'),
('MANUAL_CAPACITY','UNMASKING_MANPOWER','Unmasking manpower baseline',true,40,'{"mainOperation":"UNMASKING"}'::jsonb,'{"allowedResources":["UNMASKING"],"laborResourceCode":"UNMASKING_LABOR","parallelAllowed":true,"minOperators":1,"maxOperators":2,"operator2ThresholdWorkMinutes":180,"parallelEfficiency":0.90,"releaseMinutes":5}'::jsonb,'Default unmasking rule. Uses source/fallback min/pc work content and shared unmasking labor capacity.')
ON CONFLICT (rule_type,code) DO UPDATE SET name=EXCLUDED.name,enabled=EXCLUDED.enabled,priority=EXCLUDED.priority,condition_json=EXCLUDED.condition_json,action_json=EXCLUDED.action_json,notes=EXCLUDED.notes,updated_at=now();

INSERT INTO config_settings (setting_key,category,label,data_type,value_json,enabled,description) VALUES
('stOutput.timeModelVersion','ST_OUTPUT_MODEL','Time Model Version','string','"V020_CHEMICAL_PAINT_MANUAL_SEGMENTED"'::jsonb,true,'Finite-capacity target simulation uses segmented Chemical Line, recipe-aware Painting, and workstation + operator constrained Masking/Unmasking.')
ON CONFLICT (setting_key) DO UPDATE SET value_json=EXCLUDED.value_json,description=EXCLUDED.description,enabled=true,updated_at=now();
