-- Verification index only. Do not run this file as a SQL batch.
-- Aiven Query Editor: max 8 statements per execution.
--
-- Run one file at a time:
-- verify_st.sql      : 6 statements
-- verify_routing.sql : 5 statements
